version: "3.8"
services:
  website:
    build:
      context: Dockerfile.d/hugo-static-website
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    working_dir: /techlog-simple/exampleSite
    command: >
      hugo server
      --baseURL http://$BIND_IP_ADDR:1313
      --bind 0.0.0.0
      --buildDrafts
      --themesDir="../.."
    volumes:
      - ../:/techlog-simple
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:1313:1313"
